name: hail-shape
channels:
 - conda-forge
dependencies:
 - nb_conda
 - jupyterlab
 - tqdm
 - matplotlib
 - numpy
 - scipy
 - pandas
 - trimesh
 - stl
 - shapely
 - rtree
 - networkx
 - pyglet
 - scikit-image
 - ipympl
